"""DatabaseTest

Revision ID: 33f2233d6dc1
Revises: 9633c58c426f
Create Date: 2024-05-23 14:58:14.649019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33f2233d6dc1'
down_revision: Union[str, None] = '9633c58c426f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dept')
    op.drop_table('vication')
    op.drop_table('typeVication')
    op.drop_table('post')
    op.drop_table('worker')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('worker_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='worker_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('post_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='post_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('typeVication',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"typeVication_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='typeVication_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('vication',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('typevication_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('worker_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('startdate', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('enddate', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['typevication_id'], ['typeVication.id'], name='vication_typevication_id_fkey'),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], name='vication_worker_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vication_pkey')
    )
    op.create_table('dept',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('worker_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='dept_post_id_fkey'),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], name='dept_worker_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dept_pkey')
    )
    # ### end Alembic commands ###
